const express = require("express");
const { z } = require("zod");
const { query } = require("../db");
const { authRequired } = require("../middleware/auth");
const { tenantRequired } = require("../middleware/tenant");
const { auditLog } = require("../services/audit");
const { generateDefaultClientDocuments } = require("../services/documentAutomationService");

const router = express.Router();
router.use(authRequired, tenantRequired);

const clientSchema = z.object({
  name: z.string().min(2),
  document: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  email: z.string().email().optional().nullable(),
  address: z.string().optional().nullable(),
  autoGenerateDocuments: z.boolean().default(true),
  documentTemplates: z.array(z.enum(["procuracao","contrato_honorarios","hipossuficiencia","faa"])).optional(),
  documentData: z.record(z.any()).optional(),
  legalRepresentative: z.object({
    type: z.string().optional().nullable(),
    name: z.string().optional().nullable(),
    document: z.string().optional().nullable(),
    authority: z.string().optional().nullable()
  }).optional().nullable()
});

router.get("/", async (req, res) => {
  const result = await query("select * from clients where office_id=$1 and deleted_at is null order by created_at desc limit 500", [req.officeId]);
  res.json({ data: result.rows });
});

router.post("/", async (req, res) => {
  const input = clientSchema.parse(req.body);

  const result = await query(
    `insert into clients (office_id, name, document, phone, email, address, legal_representative)
     values ($1,$2,$3,$4,$5,$6,$7)
     returning *`,
    [req.officeId, input.name, input.document || null, input.phone || null, input.email || null, input.address || null, input.legalRepresentative || null]
  );

  let generatedDocuments = [];
  if (input.autoGenerateDocuments !== false) {
    generatedDocuments = await generateDefaultClientDocuments({
      officeId: req.officeId,
      userId: req.user.id,
      client: result.rows[0],
      templates: input.documentTemplates,
      data: input.documentData || {}
    });
  }

  await auditLog({ userId: req.user.id, officeId: req.officeId, module: "Clientes", action: "Criar cliente", entityType: "client", entityId: result.rows[0].id, detail: JSON.stringify({ generatedDocuments: generatedDocuments.length }), ip: req.ip });
  res.status(201).json({ data: result.rows[0], generatedDocuments });
});

router.put("/:id", async (req, res) => {
  const input = clientSchema.partial().parse(req.body);

  const result = await query(
    `update clients
     set name=coalesce($3,name), document=coalesce($4,document), phone=coalesce($5,phone),
         email=coalesce($6,email), address=coalesce($7,address), legal_representative=coalesce($8,legal_representative),
         updated_at=now()
     where id=$1 and office_id=$2 and deleted_at is null returning *`,
    [req.params.id, req.officeId, input.name || null, input.document || null, input.phone || null, input.email || null, input.address || null, input.legalRepresentative || null]
  );

  if (!result.rows[0]) return res.status(404).json({ error: true, message: "Cliente não encontrado." });
  await auditLog({ userId: req.user.id, officeId: req.officeId, module: "Clientes", action: "Atualizar cliente", entityType: "client", entityId: req.params.id, ip: req.ip });
  res.json({ data: result.rows[0] });
});

router.delete("/:id", async (req, res) => {
  const reason = String(req.body?.reason || "Arquivamento solicitado pelo usuário.");
  const result = await query(
    "update clients set deleted_at=now(), deleted_by=$3, deleted_reason=$4 where id=$1 and office_id=$2 and deleted_at is null returning *",
    [req.params.id, req.officeId, req.user.id, reason]
  );

  if (!result.rows[0]) return res.status(404).json({ error: true, message: "Cliente não encontrado ou já arquivado." });
  await auditLog({ userId: req.user.id, officeId: req.officeId, module: "Clientes", action: "Arquivar cliente", entityType: "client", entityId: req.params.id, detail: reason, ip: req.ip });
  res.json({ data: result.rows[0] });
});

router.patch("/:id/restore", async (req, res) => {
  const result = await query(
    "update clients set deleted_at=null, deleted_by=null, deleted_reason=null, updated_at=now() where id=$1 and office_id=$2 returning *",
    [req.params.id, req.officeId]
  );

  if (!result.rows[0]) return res.status(404).json({ error: true, message: "Cliente não encontrado." });
  await auditLog({ userId: req.user.id, officeId: req.officeId, module: "Clientes", action: "Restaurar cliente", entityType: "client", entityId: req.params.id, ip: req.ip });
  res.json({ data: result.rows[0] });
});

module.exports = router;
