const express = require("express");
const { z } = require("zod");
const { query } = require("../db");
const { authRequired } = require("../middleware/auth");
const { tenantRequired } = require("../middleware/tenant");
const { auditLog } = require("../services/audit");
const router=express.Router();
router.use(authRequired,tenantRequired);
const schema=z.object({clientId:z.string().optional(),client_id:z.string().optional(),legalBasis:z.string().optional(),legal_basis:z.string().optional(),dataCategory:z.string().optional(),data_category:z.string().optional(),retention:z.string().optional().nullable(),notes:z.string().optional().nullable()});
router.get("/",async(req,res)=>{const r=await query("select * from lgpd_records where office_id=$1 and deleted_at is null order by created_at desc limit 500",[req.officeId]);res.json({data:r.rows});});
router.post("/",async(req,res)=>{const b=schema.parse(req.body);const r=await query("insert into lgpd_records (office_id,client_id,legal_basis,data_category,retention,notes,created_by) values ($1,$2,$3,$4,$5,$6,$7) returning *",[req.officeId,b.clientId||b.client_id,b.legalBasis||b.legal_basis,b.dataCategory||b.data_category,b.retention||null,b.notes||null,req.user.id]);await auditLog({userId:req.user.id,officeId:req.officeId,module:"LGPD",action:"Criar registro",entityType:"lgpd_record",entityId:r.rows[0].id,ip:req.ip});res.status(201).json({data:r.rows[0]});});
module.exports=router;
