const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
function assert(condition, message) { if (!condition) { console.error("FALHA:", message); process.exitCode = 1; } else console.log("OK:", message); }

const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const app = fs.readFileSync(path.join(root, "public", "app-comercial.html"), "utf8");
const api = fs.readFileSync(path.join(root, "public", "api-client.js"), "utf8");
const clientsRoute = fs.readFileSync(path.join(root, "src/routes/clients.js"), "utf8");
const workspaceRoute = fs.readFileSync(path.join(root, "src/routes/workspace.js"), "utf8");
const server = fs.readFileSync(path.join(root, "server.js"), "utf8");

assert(pkg.version === "2.5.0", "versão 2.5.0");
assert(fs.existsSync(path.join(root, "src/services/documentAutomationService.js")), "serviço documentAutomationService existe");
assert(clientsRoute.includes("generateDefaultClientDocuments"), "clientes integra geração automática de documentos");
assert(clientsRoute.includes("autoGenerateDocuments"), "clientes aceita flag autoGenerateDocuments");
assert(clientsRoute.includes("generatedDocuments"), "resposta do cadastro de cliente devolve generatedDocuments");
assert(app.includes("clientAutoDocs"), "UI cliente possui opção de gerar documentos automáticos");
assert(app.includes("documentTemplates") && app.includes("documentData"), "UI envia documentTemplates/documentData");
assert(app.includes("Documentos automáticos gerados"), "UI informa documentos gerados no cadastro do cliente");
assert(api.includes('if (path === "/clients" && opts.method === "POST")'), "demo API intercepta cadastro de cliente");
assert(api.includes("gd-auto-procuracao") && api.includes("gd-auto-faa"), "demo API gera documentos automáticos");
assert(workspaceRoute.includes("/generate-document"), "workspace mantém geração manual de documento");
assert(server.includes("/api/workspace") && server.includes("/api/clients"), "server preserva workspace e clients");
["noticesView","chatView","publicationsView","agendaView","calendarView","leadsView","calculatorsView","saasView","docautoView"].forEach(token => assert(app.includes(token), `módulo preservado ${token}`));
